import java.util.Collections;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
final class Library {

    public static void main(String... args){

    }

    public static List<String> reverseString(List<String> stringToReverse) {
        if(stringToReverse == null || stringToReverse.isEmpty()){
            return Collections.emptyList();
        }
        return Collections.singletonList("oof");
    }
}
